### ISSUE TITLE
Executing on Linux via Mono crashes with SIGABRT

### ISSUE THREAD

**Issue by DKedrowitsch** [Trinity-11/FoenixIDE#55]
Trying both the standalone version 7.0.0 bundled with Mono that was provided to me back in January on the Foenix Retro Systems Discord, or the current release crashes.  

The application launches and I can see the UI for a few seconds, then it suddenly crashes.

System is Arch based x86_64 on a Ryzen 7840HS powered laptop currently running Linux 6.8.1.  Mono is version 6.12.0.  DE is Plasma 6.0.2 on Wayland.

I've attached the mono_crash file, and below is the output when launched from CLI.

[mono_crash.8153863cb.1.json](https://github.com/Trinity-11/FoenixIDE/files/14732146/mono_crash.8153863cb.1.json)

Any help figuring out how to get this to run would be greatly appreciated!!

```
=================================================================
Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
Native stacktrace:
=================================================================
0x63178d71af19 - mono :
0x63178d6c4437 - mono :
0x63178d7098e5 - mono :
0x40bd67ef - Unknown

=================================================================
Telemetry Dumper:
=================================================================
Pkilling 0x140243284002496x from 0x140243584680064x
Pkilling 0x140243525174976x from 0x140243584680064x
Pkilling 0x140243369985728x from 0x140243584680064x
Pkilling 0x140243292391104x from 0x140243584680064x
Pkilling 0x140243378374336x from 0x140243584680064x
Pkilling 0x140243397248704x from 0x140243584680064x
Pkilling 0x140243386762944x from 0x140243584680064x
Pkilling 0x140243405637312x from 0x140243584680064x
Pkilling 0x140243288196800x from 0x140243584680064x
Pkilling 0x140243374180032x from 0x140243584680064x
Pkilling 0x140243422414528x from 0x140243584680064x
Pkilling 0x140243393054400x from 0x140243584680064x
Pkilling 0x140243296585408x from 0x140243584680064x
Pkilling 0x140243382568640x from 0x140243584680064x
Entering thread summarizer pause from 0x140243584680064x
Finished thread summarizer pause from 0x140243584680064x.
Failed to create breadcrumb file (null)/crash_hash_0x81538879d

Waiting for dumping threads to resume

=================================================================
External Debugger Dump:
=================================================================
[New LWP 74754]
[New LWP 74755]
[New LWP 74756]
[New LWP 74757]
[New LWP 74766]
[New LWP 74767]
[New LWP 74768]
[New LWP 74769]
[New LWP 74770]
[New LWP 74771]
[New LWP 74772]
[New LWP 74773]
[New LWP 74774]
[New LWP 74775]
[New LWP 74776]

This GDB supports auto-downloading debuginfo from the following URLs:
<https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
warning: File "/usr/bin/mono-sgen-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
add-auto-load-safe-path /usr/bin/mono-sgen-gdb.py
line to your configuration file "/home/dieter/.config/gdb/gdbinit".
To completely disable this security protection add
set auto-load safe-path /
line to your configuration file "/home/dieter/.config/gdb/gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
info "(gdb)Auto-loading safe path"
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007f8d011b2ec7 in wait4 () from /usr/lib/libc.so.6
Id   Target Id                                           Frame
* 1    Thread 0x7f8d010c0080 (LWP 74753) "mono"            0x00007f8d011b2ec7 in wait4 () from /usr/lib/libc.so.6
2    Thread 0x7f8d002006c0 (LWP 74754) "SGen worker"     0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
3    Thread 0x7f8cfd8006c0 (LWP 74755) "Finalizer"       0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
4    Thread 0x7f8cf76006c0 (LWP 74756) "mono"            0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
5    Thread 0x7f8cf66006c0 (LWP 74757) "mono"            0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
6    Thread 0x7f8cf5e006c0 (LWP 74766) "mono"            0x0000000040b7a43d in ?? ()
7    Thread 0x7f8cf5a006c0 (LWP 74767) "Timer-Scheduler" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
8    Thread 0x7f8cf54006c0 (LWP 74768) "Timer-Scheduler" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
9    Thread 0x7f8cf50006c0 (LWP 74769) "Thread Pool Wor" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
10   Thread 0x7f8cf4c006c0 (LWP 74770) "Thread Pool Wor" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
11   Thread 0x7f8cf48006c0 (LWP 74771) "Thread Pool Wor" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
12   Thread 0x7f8cf44006c0 (LWP 74772) "Thread Pool Wor" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
13   Thread 0x7f8cefe006c0 (LWP 74773) "Thread Pool Wor" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
14   Thread 0x7f8cefa006c0 (LWP 74774) "Thread Pool Wor" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
15   Thread 0x7f8cef6006c0 (LWP 74775) "Thread Pool Wor" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6
16   Thread 0x7f8cef2006c0 (LWP 74776) "Thread Pool Wor" 0x00007f8d01148ebe in ?? () from /usr/lib/libc.so.6

Thread 16 (Thread 0x7f8cef2006c0 (LWP 74776) "Thread Pool Wor"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0115425b in ??? () at /usr/lib/libc.so.6
#2  0x000063178d92a2bd in ??? ()
#3  0x000063178d8d3b11 in ??? ()
#4  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#5  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7f8cef6006c0 (LWP 74775) "Thread Pool Wor"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0115425b in ??? () at /usr/lib/libc.so.6
#2  0x000063178d92a2bd in ??? ()
#3  0x000063178d8d3b11 in ??? ()
#4  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#5  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 14 (Thread 0x7f8cefa006c0 (LWP 74774) "Thread Pool Wor"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0115425b in ??? () at /usr/lib/libc.so.6
#2  0x000063178d92a2bd in ??? ()
#3  0x000063178d8d3b11 in ??? ()
#4  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#5  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 13 (Thread 0x7f8cefe006c0 (LWP 74773) "Thread Pool Wor"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0115425b in ??? () at /usr/lib/libc.so.6
#2  0x000063178d92a2bd in ??? ()
#3  0x000063178d8d3b11 in ??? ()
#4  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#5  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 12 (Thread 0x7f8cf44006c0 (LWP 74772) "Thread Pool Wor"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0115425b in ??? () at /usr/lib/libc.so.6
#2  0x000063178d92a2bd in ??? ()
#3  0x000063178d8d3b11 in ??? ()
#4  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#5  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 11 (Thread 0x7f8cf48006c0 (LWP 74771) "Thread Pool Wor"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0115425b in ??? () at /usr/lib/libc.so.6
#2  0x000063178d92a2bd in ??? ()
#3  0x000063178d8d3b11 in ??? ()
#4  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#5  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7f8cf4c006c0 (LWP 74770) "Thread Pool Wor"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0115425b in ??? () at /usr/lib/libc.so.6
#2  0x000063178d92a2bd in ??? ()
#3  0x000063178d8d3b11 in ??? ()
#4  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#5  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7f8cf50006c0 (LWP 74769) "Thread Pool Wor"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0115425b in ??? () at /usr/lib/libc.so.6
#2  0x000063178d92a2bd in ??? ()
#3  0x000063178d8d3b11 in ??? ()
#4  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#5  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7f8cf54006c0 (LWP 74768) "Timer-Scheduler"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0114ba65 in pthread_cond_timedwait () at /usr/lib/libc.so.6
#2  0x000063178d98f7a0 in ??? ()
#3  0x000063178d999536 in ??? ()
#4  0x000063178d92b339 in ??? ()
#5  0x000063178d8d3b11 in ??? ()
#6  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#7  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f8cf5a006c0 (LWP 74767) "Timer-Scheduler"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0114b750 in pthread_cond_wait () at /usr/lib/libc.so.6
#2  0x000063178d98f7fe in ??? ()
#3  0x000063178d9b3827 in ??? ()
#4  0x000063178d8ea0f8 in ??? ()
#5  0x000063178d9b3462 in ??? ()
#6  0x000063178d869adf in ??? ()
#7  0x0000000040bce082 in ??? ()
#8  0x00007f8d00678370 in ??? ()
#9  0x00007f8d00678468 in ??? ()
#10 0x00007f8d006782a0 in ??? ()
#11 0x0000000000000000 in ??? ()

Thread 6 (Thread 0x7f8cf5e006c0 (LWP 74766) "mono"):
#0  0x0000000040b7a43d in ??? ()
#1  0x00000000003e007d in ??? ()
#2  0x00007f8d005c17c0 in ??? ()
#3  0x00007f8cf7b442b0 in ??? ()
#4  0x0000000040bc0540 in ??? ()
#5  0x00007f8d00675a50 in ??? ()
#6  0x00007f8cf5dffb00 in ??? ()
#7  0x00007f8d00675be8 in ??? ()
#8  0x00007f8d006759d0 in ??? ()
#9  0x00007f8d00675aa0 in ??? ()
#10 0x00007f8d005c17c0 in ??? ()
#11 0x0000000000000000 in ??? ()

Thread 5 (Thread 0x7f8cf66006c0 (LWP 74757) "mono"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0114ba65 in pthread_cond_timedwait () at /usr/lib/libc.so.6
#2  0x000063178d98f7a0 in ??? ()
#3  0x000063178d999536 in ??? ()
#4  0x000063178d85e7e9 in ??? ()
#5  0x0000000040b2cd7d in ??? ()
#6  0x00007f8d0074b050 in ??? ()
#7  0x0000000000000001 in ??? ()
#8  0x00007f8d0074b438 in ??? ()
#9  0x0000000000000000 in ??? ()

Thread 4 (Thread 0x7f8cf76006c0 (LWP 74756) "mono"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0114b750 in pthread_cond_wait () at /usr/lib/libc.so.6
#2  0x000063178d98f7fe in ??? ()
#3  0x000063178d9b3827 in ??? ()
#4  0x000063178d8ea0f8 in ??? ()
#5  0x000063178d9b3462 in ??? ()
#6  0x000063178d869adf in ??? ()
#7  0x0000000040bce082 in ??? ()
#8  0x00007f8d0073e5f8 in ??? ()
#9  0x00007f8d006a0c00 in ??? ()
#10 0x00007f8d007b9588 in ??? ()
#11 0x0000000000000000 in ??? ()

Thread 3 (Thread 0x7f8cfd8006c0 (LWP 74755) "Finalizer"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d01154470 in ??? () at /usr/lib/libc.so.6
#2  0x000063178d91f6a6 in ??? ()
#3  0x000063178d8d3b11 in ??? ()
#4  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#5  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f8d002006c0 (LWP 74754) "SGen worker"):
#0  0x00007f8d01148ebe in ??? () at /usr/lib/libc.so.6
#1  0x00007f8d0114b750 in pthread_cond_wait () at /usr/lib/libc.so.6
#2  0x000063178d97b855 in ??? ()
#3  0x00007f8d0114c55a in ??? () at /usr/lib/libc.so.6
#4  0x00007f8d011c9a3c in ??? () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f8d010c0080 (LWP 74753) "mono"):
#0  0x00007f8d011b2ec7 in wait4 () at /usr/lib/libc.so.6
#1  0x000063178d71b1a6 in ??? ()
#2  0x000063178d6c4437 in ??? ()
#3  0x000063178d7098e5 in ??? ()
#4  0x0000000040bd67ef in ??? ()
#5  0x0000000000000008 in ??? ()
#6  0x0000000000000008 in ??? ()
#7  0x0000000000000180 in ??? ()
#8  0x0000000000000280 in ??? ()
#9  0x00000000000001e0 in ??? ()
#10 0x0000000000000000 in ??? ()
[Inferior 1 (process 74753) detached]

=================================================================
Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x40bd67ef):0x40bd67df  8b 85 b8 fe ff ff 48 03 c1 48 63 8d 48 fe ffff  ......H..Hc.H...
0x40bd67ef  89 08 48 63 85 78 fe ff ff ff c0 89 85 78 fe ff  ..Hc.x.......x..
0x40bd67ff  ff 48 63 85 48 ff ff ff 39 85 78 fe ff ff 0f 8c  .Hc.H...9.x.....
0x40bd680f  55 ff ff ff 49 8b c5 83 e0 04 83 f8 04 74 10 41  U...I........t.A

=================================================================
Managed Stacktrace:
=================================================================
at FoenixIDE.Display.Gpu:Gpu_Paint <0x00c5f>
at System.Windows.Forms.Control:OnPaint <0x0008f>
at System.Windows.Forms.Control:WmPaint <0x0019b>
at System.Windows.Forms.Control:WndProc <0x00253>
at System.Windows.Forms.ScrollableControl:WndProc <0x00033>
at System.Windows.Forms.ContainerControl:WndProc <0x00073>
at System.Windows.Forms.UserControl:WndProc <0x00083>
at ControlWindowTarget:OnMessage <0x0003c>
at ControlNativeWindow:WndProc <0x00052>
at System.Windows.Forms.NativeWindow:WndProc <0x0037b>
at <Module>:runtime_invoke_intptr_intptr_int_intptr_intptr <0x000a9>
at <unknown> <0xffffffff>
at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x000ad>
at System.Reflection.RuntimeMethodInfo:Invoke <0x0010a>
at System.Reflection.MethodBase:Invoke <0x00047>
at System.Delegate:DynamicInvokeImpl <0x00271>
at System.MulticastDelegate:DynamicInvokeImpl <0x00049>
at System.Delegate:DynamicInvoke <0x00036>
at System.Windows.Forms.XplatUIDriverSupport:ExecutionCallback <0x0005a>
at System.Windows.Forms.XplatUIDriverSupport:ExecuteClientMessage <0x00083>
at System.Windows.Forms.XplatUIX11:GetMessage <0x04507>
at System.Windows.Forms.XplatUI:GetMessage <0x00064>
at System.Windows.Forms.Application:RunLoop <0x00aab>
at System.Windows.Forms.Application:Run <0x0007f>
at System.Windows.Forms.Application:Run <0x0004f>
at FoenixIDE.Program:Main <0x0014f>
at <Module>:runtime_invoke_void_object <0x00091>
=================================================================
fish: Job 1, 'mono FoenixIDE.exe' terminated by signal SIGABRT (Abort)

╭─dieter@elitebook in ~/Downloads/FoenixIDE as 🧙 took 2s
[⚡] ×
```

**Comment by dtremblay** [comment]
To be frank, I never supported Linux.  Another member of the Foenix community is providing the Linux port.  You should check with @marnuba.
